## Beauty of Numpy

### Layer of a Neuron in Numpy

You have a hidden layer with 3 neurons and 4 input , each neuron receives 4 weights how do we represent this as a numpy vector?

In [3]:
import numpy as np 

What happpens when you change the dimension of x? in first it is a 2x2 matrix in second run it is simply a vector

In [9]:
np.random.seed(42)
x = np.random.rand(1,4)
print(x)

weights = np.random.rand(4,3)
print(weights)

ans= np.dot(x,weights)
print(ans)

[[0.37454012 0.95071431 0.73199394 0.59865848]]
[[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
[[1.02410763 1.44873404 1.41406901]]


In [10]:
np.random.seed(42)
x = np.random.rand(4)
print(x)

weights = np.random.rand(4,3)
print(weights)

ans= np.dot(x,weights)
print(ans)

[0.37454012 0.95071431 0.73199394 0.59865848]
[[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
[1.02410763 1.44873404 1.41406901]


Here we do the final neuron layer

In [12]:
np.random.seed(42)

x = np.random.rand(4)
b= np.random.rand(3)
weights = np.random.rand(4,3)

ans= np.dot(x,weights)+b


### Data coming in batch 